config/routes.rb
Rails.application.routes.draw do

  root 'greet#guest'
  
  get 'greet/guest'
  get 'greet/member'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.sso_authenticate(token)
    where(token: token).first || false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  def not_authenticated
    redirect_to token_url
  end

  private
  
  def token_url
    "#{ENV['AUTH_URL']}/token?key=#{public_key(rsa)}"
  end

  def login_from_session
    token = redis.get("token:#{session.id}")
    return false if token.blank?
    sso_login(token)
  end
  
  def login_from_other_sources
    return false if params[:token].blank? || !restore_private_key
    begin
      token = rebuilt_rsa.private_decrypt(
        Base64.urlsafe_decode64(params[:token])
      )
    rescue 
      false
    else
      sso_login(token)
    end
  end

  def sso_login(token)
    @current_user = nil
    user = User.sso_authenticate(token)
    return nil unless user
    old_session = session.dup.to_hash
    reset_sorcery_session
    old_session.each_pair do |k, v|
      session[k.to_sym] = v
    end
    store_token(token)
    session.delete(:return_to_url)
    @current_user = user
  end
 
  def rebuilt_rsa
    rsa(restore_private_key)
  end

  def store_private_key(key)
    redis.setex("private_key:#{session.id}", 120, key)
  end

  def restore_private_key
    redis.get("private_key:#{session.id}")
  end

  def store_token(token)
    redis.setex("token:#{session.id}", 60, token)
  end

  def public_key(pair)
    store_private_key(pair.export)
    Base64.urlsafe_encode64(
      pair.public_key.export
    )
  end

  def rsa(param = 2048)
    OpenSSL::PKey::RSA.new param
  end

  def redis
    Redis.new(url: ENV['REDIS_URL'])
  end
end

app/controllers/greet_controller.rb
class GreetController < ApplicationController
  skip_before_action :require_login, only: [:guest]
  def guest
  end

  def member
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_url
    "#{ENV['AUTH_URL']}/profile"
  end
end

app/views/greet/guest.html.slim
h1 Greet#guest
h3 Hello, newcomer!

app/views/greet/member.html.slim
h1 Greet#member
h3 Hello, #{current_user.name || current_user.email}

app/views/layouts/application.html.slim
doctype html
html
  head
    title Teachbase Client
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    = action_cable_meta_tag
    = favicon_link_tag "apple-touch-icon.png",
                         rel: "apple-touch-icon",
                         sizes: "100x100",
                         type: "image/png"
  body
    nav.navbar.navbar-default role="navigation"
      .row
        .col-md-8.col-md-offset-2
          /! Brand and toggle get grouped for better mobile display
          .navbar-header
            = link_to 'Teachbase Client', root_path, class: 'navbar-brand'
          ul.nav.navbar-nav.navbar-right
            li= link_to 'guest', greet_guest_path
            li= link_to 'member', greet_member_path
            - if logged_in?
              li
                = link_to 'profile', profile_url
              
    .row
      .col-md-7.col-md-offset-2
        - if flash.keys.any?
          - unless alert.nil?
            .alert.alert-warning role="alert"
              = alert
          - unless notice.nil?
            .alert.alert-success role="alert"
              = notice

        p session.id: #{session.id}
        = yield